### ISSUE TITLE
What is the draft layout for the design?

### ISSUE THREAD

**Issue by alixedi** [alixedi/gitdash#1]
I really think that out Dripl design will do for the moment.

![gitdash_design_draft](https://cloud.githubusercontent.com/assets/3349430/12887518/d6d478fa-ce6c-11e5-9a82-24c3f48740b4.jpg)

**Comment by alixedi** [comment]
Tagging @osamakhn for input.

**Comment by gh-osama** [comment]
This should work fine but need to figure out a little tag/widget/fine print on the page which handles the bit 'viral' bit  ... like the 'Fork me on Github' ribbon we often see for gh-pages sites ... Mocking it up

**Comment by alixedi** [comment]
In theory, we _can_ have the GitHub ribbon 🙌

**Comment by alixedi** [comment]
Here come the ribbons: https://github.com/blog/273-github-ribbons

**Comment by alixedi** [comment]
I will close this as soon as we take care of the header.

**Comment by alixedi** [comment]
I am freshening thing up. Let me know if yall like the new goth-chick look :)
