### ISSUE TITLE
Data Source at Client Side

### ISSUE THREAD

**Issue by alirazabhayani** [alixedi/gitdash#8]
As easy as pasting comma separated values in an input/Text box while in DataView Mode and pressing the button "AnalyzeThis" to see the visualizations. All Client End.

Example:
http://davidguttman.github.io/react-pivot/

Client Side Data can also be achieved by github's new feature of Drag and Drop any file easily to your repo and BAM! , you can analyze your data with a click of button! 
Checkout how easy it is now to upload a file. An amateur with little knowledge of github interface can do it:
https://github.com/blog/2105-upload-files-to-your-repositories

**Comment by alixedi** [comment]
If we let the user select/paste CSV data on the frontend, we have no way of saving (committing) this to the underlying GitHub repository.
